# Generated by Django 3.2.8 on 2021-10-19 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_course_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='deadline',
            field=models.CharField(max_length=20),
        ),
    ]
